events {
    worker_connections 1024;
}

http {
    upstream backend_cluster {
        # Round Robin by default
        server backend:3000;
    }

    server {
        listen 80;
        
        # Simulating CloudFront / ALB routing
        location /api/ {
            proxy_pass http://backend_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /health {
            proxy_pass http://backend_cluster/health;
        }

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
